In [1]:
import joblib

def prediction_billet_RL(data):

    # Copie des données pour ne pas modifier df
    resultats = data.copy()

    # On place l'identifiant du billet en index
    resultats = resultats.set_index("id")

    # Chargement du pipeline complet :
    # imputation + standardisation + RL
    pipeline_RL = joblib.load(
        "/content/drive/MyDrive/projet 12/modele_RL.joblib"
    )

    # Récupération des variables utilisées pendant l'entraînement
    variables = list(pipeline_RL.feature_names_in_)

    # Vérification des colonnes manquantes
    colonnes_manquantes = [
        colonne for colonne in variables
        if colonne not in resultats.columns
    ]

    if colonnes_manquantes:
        raise ValueError(
            f"Colonnes manquantes dans le fichier : {colonnes_manquantes}"
        )

    # Sélection des variables brutes dans le même ordre
    X = resultats[variables]

    # Le pipeline réalise automatiquement :
    # l'imputation, la standardisation et la prédiction
    prediction = pipeline_RL.predict(X)

    # Ajout des prédictions
    resultats["Prédiction"] = prediction

    # Conversion des résultats en texte
    resultats["Nature du billet"] = resultats["Prédiction"].map({
        1: "Authentique",
        0: "Contrefait"
    })

    return resultats

In [2]:
#Charger le fichier des nouveaux billets
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/projet 12/test billets_production.csv')
df.head()

   diagonal  height_left  height_right  margin_low  margin_up  length   id
0    171.76       104.01        103.54        5.21       3.30  111.42  A_1
1    171.87       104.17        104.13        6.00       3.31  112.09  A_2
2    172.00       104.58        104.29        4.99       3.39  111.57  A_3
3    172.49       104.55        104.34        4.44       3.03  113.20  A_4
4    171.65       103.63        103.56        3.77       3.16  113.33  A_5

In [3]:
resultats = prediction_billet_RL(df)

display(resultats)

,diagonal,height_left,height_right,margin_low,margin_up,length,Prédiction,Nature du billet
id,,,,,,,,
A_1,171.76,104.01,103.54,5.21,3.30,111.42,0,Contrefait
A_2,171.87,104.17,104.13,6.00,3.31,112.09,0,Contrefait
A_3,172.00,104.58,104.29,4.99,3.39,111.57,0,Contrefait
A_4,172.49,104.55,104.34,4.44,3.03,113.20,1,Authentique
A_5,171.65,103.63,103.56,3.77,3.16,113.33,1,Authentique